import {cp,mkdir,writeFile,chmod,rm} from 'node:fs/promises';
const root='work/portable-v1.2/semantic-instruments';
await rm(root,{recursive:true,force:true});
await mkdir(root,{recursive:true});
await cp('dist',root+'/site',{recursive:true});
await cp('docs',root+'/docs',{recursive:true});
await cp('scripts/serve.py',root+'/serve.py');
await mkdir(root+'/examples',{recursive:true});
await cp('tests/fixtures/portable-example.json',root+'/examples/vectors-and-scores.json');
await cp('tests/fixtures/unlabeled.json',root+'/examples/unlabeled-vectors.json');
await cp('tests/fixtures/linked-preview.json',root+'/examples/linked-thumbnail.json');
await cp('examples/image-toy-model.silab',root+'/examples/image-toy-model.silab');
await writeFile(root+'/Start.command','#!/bin/sh\ncd "$(dirname "$0")"\nexec python3 serve.py --directory site --port "${1:-8773}"\n');
await chmod(root+'/Start.command',0o755);
await cp('START_HERE.md', root+'/START_HERE.md');
console.log(root);
